# Generated by Django 3.0 on 2020-01-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_limit', models.IntegerField()),
                ('com_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled')], default=1)),
                ('hours_worked', models.IntegerField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Work')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('com_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('worker_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Worker')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Finished')])),
                ('work_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField()),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WorkPlace')),
            ],
        ),
    ]
