# Generated by Django 3.0 on 2020-01-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='com_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='polls.Company'),
        ),
    ]
