# Generated by Django 3.0 on 2020-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200104_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Finished')], default=None),
            preserve_default=False,
        ),
    ]
