# Generated by Django 3.0 on 2020-01-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200104_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='workplace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='worktimes', to='polls.WorkPlace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='work_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='polls.Work'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='worker_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='polls.Worker'),
        ),
    ]
